-- StudyHub – Supabase schema (PostgreSQL)
-- Run this in the SQL editor of your Supabase project (or via `supabase db push`).
--
-- Every table mirrors the local SQLite table and adds `rev bigint`, which the
-- trigger below increments on every update. Row Level Security restricts all
-- access to rows with user_id = auth.uid(). Timestamps are ISO-8601 strings
-- generated by the clients (UTC) and stored as text so they compare exactly like
-- in SQLite; `rev` is the server-side version number.

create extension if not exists "pgcrypto";

-- Server-side revision counter -------------------------------------------------
create or replace function public.studyhub_bump_rev()
returns trigger
language plpgsql
as $$
begin
  if tg_op = 'INSERT' then
    new.rev := 1;
  else
    new.rev := coalesce(old.rev, 0) + 1;
  end if;
  -- Server time of the write; clients pull by this cursor so that rows with
  -- older client timestamps (edited offline, synced later) are never missed.
  new.synced_at := now();
  return new;
end;
$$;

-- subjects -----------------------------------------------------------------
create table if not exists public.subjects (
  id uuid primary key,
  user_id uuid not null references auth.users (id) on delete cascade,
  created_at text not null,
  updated_at text not null,
  deleted_at text,
  rev bigint not null default 0,
  synced_at timestamptz not null default now(),
  name text not null,
  color text not null default '#3b5bdb',
  teacher text,
  room text,
  sort_order integer not null default 0
);
create index if not exists idx_subjects_user_synced on public.subjects (user_id, synced_at);
drop trigger if exists trg_subjects_rev on public.subjects;
create trigger trg_subjects_rev before insert or update on public.subjects
  for each row execute function public.studyhub_bump_rev();
alter table public.subjects enable row level security;
drop policy if exists "subjects_owner_select" on public.subjects;
drop policy if exists "subjects_owner_insert" on public.subjects;
drop policy if exists "subjects_owner_update" on public.subjects;
create policy "subjects_owner_select" on public.subjects for select using (user_id = auth.uid());
create policy "subjects_owner_insert" on public.subjects for insert with check (user_id = auth.uid());
create policy "subjects_owner_update" on public.subjects for update using (user_id = auth.uid()) with check (user_id = auth.uid());
-- No delete policy: rows are soft-deleted via deleted_at, never removed.

-- timetable_slots -----------------------------------------------------------------
create table if not exists public.timetable_slots (
  id uuid primary key,
  user_id uuid not null references auth.users (id) on delete cascade,
  created_at text not null,
  updated_at text not null,
  deleted_at text,
  rev bigint not null default 0,
  synced_at timestamptz not null default now(),
  subject_id uuid,
  weekday integer not null,
  start_time text not null,
  end_time text not null,
  room text,
  week_type text not null default 'all'
);
create index if not exists idx_timetable_slots_user_synced on public.timetable_slots (user_id, synced_at);
drop trigger if exists trg_timetable_slots_rev on public.timetable_slots;
create trigger trg_timetable_slots_rev before insert or update on public.timetable_slots
  for each row execute function public.studyhub_bump_rev();
alter table public.timetable_slots enable row level security;
drop policy if exists "timetable_slots_owner_select" on public.timetable_slots;
drop policy if exists "timetable_slots_owner_insert" on public.timetable_slots;
drop policy if exists "timetable_slots_owner_update" on public.timetable_slots;
create policy "timetable_slots_owner_select" on public.timetable_slots for select using (user_id = auth.uid());
create policy "timetable_slots_owner_insert" on public.timetable_slots for insert with check (user_id = auth.uid());
create policy "timetable_slots_owner_update" on public.timetable_slots for update using (user_id = auth.uid()) with check (user_id = auth.uid());
-- No delete policy: rows are soft-deleted via deleted_at, never removed.

-- tasks -----------------------------------------------------------------
create table if not exists public.tasks (
  id uuid primary key,
  user_id uuid not null references auth.users (id) on delete cascade,
  created_at text not null,
  updated_at text not null,
  deleted_at text,
  rev bigint not null default 0,
  synced_at timestamptz not null default now(),
  title text not null,
  description text,
  subject_id uuid,
  due_at text,
  priority integer not null default 2,
  status text not null default 'open',
  reminder_at text,
  recurrence text,
  completed_at text
);
create index if not exists idx_tasks_user_synced on public.tasks (user_id, synced_at);
drop trigger if exists trg_tasks_rev on public.tasks;
create trigger trg_tasks_rev before insert or update on public.tasks
  for each row execute function public.studyhub_bump_rev();
alter table public.tasks enable row level security;
drop policy if exists "tasks_owner_select" on public.tasks;
drop policy if exists "tasks_owner_insert" on public.tasks;
drop policy if exists "tasks_owner_update" on public.tasks;
create policy "tasks_owner_select" on public.tasks for select using (user_id = auth.uid());
create policy "tasks_owner_insert" on public.tasks for insert with check (user_id = auth.uid());
create policy "tasks_owner_update" on public.tasks for update using (user_id = auth.uid()) with check (user_id = auth.uid());
-- No delete policy: rows are soft-deleted via deleted_at, never removed.

-- exams -----------------------------------------------------------------
create table if not exists public.exams (
  id uuid primary key,
  user_id uuid not null references auth.users (id) on delete cascade,
  created_at text not null,
  updated_at text not null,
  deleted_at text,
  rev bigint not null default 0,
  synced_at timestamptz not null default now(),
  title text not null,
  subject_id uuid,
  date text not null,
  topics text,
  weight double precision not null default 1,
  reminder_at text
);
create index if not exists idx_exams_user_synced on public.exams (user_id, synced_at);
drop trigger if exists trg_exams_rev on public.exams;
create trigger trg_exams_rev before insert or update on public.exams
  for each row execute function public.studyhub_bump_rev();
alter table public.exams enable row level security;
drop policy if exists "exams_owner_select" on public.exams;
drop policy if exists "exams_owner_insert" on public.exams;
drop policy if exists "exams_owner_update" on public.exams;
create policy "exams_owner_select" on public.exams for select using (user_id = auth.uid());
create policy "exams_owner_insert" on public.exams for insert with check (user_id = auth.uid());
create policy "exams_owner_update" on public.exams for update using (user_id = auth.uid()) with check (user_id = auth.uid());
-- No delete policy: rows are soft-deleted via deleted_at, never removed.

-- folders -----------------------------------------------------------------
create table if not exists public.folders (
  id uuid primary key,
  user_id uuid not null references auth.users (id) on delete cascade,
  created_at text not null,
  updated_at text not null,
  deleted_at text,
  rev bigint not null default 0,
  synced_at timestamptz not null default now(),
  name text not null,
  parent_id uuid,
  kind text not null
);
create index if not exists idx_folders_user_synced on public.folders (user_id, synced_at);
drop trigger if exists trg_folders_rev on public.folders;
create trigger trg_folders_rev before insert or update on public.folders
  for each row execute function public.studyhub_bump_rev();
alter table public.folders enable row level security;
drop policy if exists "folders_owner_select" on public.folders;
drop policy if exists "folders_owner_insert" on public.folders;
drop policy if exists "folders_owner_update" on public.folders;
create policy "folders_owner_select" on public.folders for select using (user_id = auth.uid());
create policy "folders_owner_insert" on public.folders for insert with check (user_id = auth.uid());
create policy "folders_owner_update" on public.folders for update using (user_id = auth.uid()) with check (user_id = auth.uid());
-- No delete policy: rows are soft-deleted via deleted_at, never removed.

-- notes -----------------------------------------------------------------
create table if not exists public.notes (
  id uuid primary key,
  user_id uuid not null references auth.users (id) on delete cascade,
  created_at text not null,
  updated_at text not null,
  deleted_at text,
  rev bigint not null default 0,
  synced_at timestamptz not null default now(),
  title text not null,
  content_markdown text not null default '',
  subject_id uuid,
  folder_id uuid,
  is_pinned integer not null default 0
);
create index if not exists idx_notes_user_synced on public.notes (user_id, synced_at);
drop trigger if exists trg_notes_rev on public.notes;
create trigger trg_notes_rev before insert or update on public.notes
  for each row execute function public.studyhub_bump_rev();
alter table public.notes enable row level security;
drop policy if exists "notes_owner_select" on public.notes;
drop policy if exists "notes_owner_insert" on public.notes;
drop policy if exists "notes_owner_update" on public.notes;
create policy "notes_owner_select" on public.notes for select using (user_id = auth.uid());
create policy "notes_owner_insert" on public.notes for insert with check (user_id = auth.uid());
create policy "notes_owner_update" on public.notes for update using (user_id = auth.uid()) with check (user_id = auth.uid());
-- No delete policy: rows are soft-deleted via deleted_at, never removed.

-- note_tags -----------------------------------------------------------------
create table if not exists public.note_tags (
  id uuid primary key,
  user_id uuid not null references auth.users (id) on delete cascade,
  created_at text not null,
  updated_at text not null,
  deleted_at text,
  rev bigint not null default 0,
  synced_at timestamptz not null default now(),
  note_id uuid not null,
  tag text not null
);
create index if not exists idx_note_tags_user_synced on public.note_tags (user_id, synced_at);
drop trigger if exists trg_note_tags_rev on public.note_tags;
create trigger trg_note_tags_rev before insert or update on public.note_tags
  for each row execute function public.studyhub_bump_rev();
alter table public.note_tags enable row level security;
drop policy if exists "note_tags_owner_select" on public.note_tags;
drop policy if exists "note_tags_owner_insert" on public.note_tags;
drop policy if exists "note_tags_owner_update" on public.note_tags;
create policy "note_tags_owner_select" on public.note_tags for select using (user_id = auth.uid());
create policy "note_tags_owner_insert" on public.note_tags for insert with check (user_id = auth.uid());
create policy "note_tags_owner_update" on public.note_tags for update using (user_id = auth.uid()) with check (user_id = auth.uid());
-- No delete policy: rows are soft-deleted via deleted_at, never removed.

-- note_files -----------------------------------------------------------------
create table if not exists public.note_files (
  id uuid primary key,
  user_id uuid not null references auth.users (id) on delete cascade,
  created_at text not null,
  updated_at text not null,
  deleted_at text,
  rev bigint not null default 0,
  synced_at timestamptz not null default now(),
  note_id uuid not null,
  file_id uuid not null
);
create index if not exists idx_note_files_user_synced on public.note_files (user_id, synced_at);
drop trigger if exists trg_note_files_rev on public.note_files;
create trigger trg_note_files_rev before insert or update on public.note_files
  for each row execute function public.studyhub_bump_rev();
alter table public.note_files enable row level security;
drop policy if exists "note_files_owner_select" on public.note_files;
drop policy if exists "note_files_owner_insert" on public.note_files;
drop policy if exists "note_files_owner_update" on public.note_files;
create policy "note_files_owner_select" on public.note_files for select using (user_id = auth.uid());
create policy "note_files_owner_insert" on public.note_files for insert with check (user_id = auth.uid());
create policy "note_files_owner_update" on public.note_files for update using (user_id = auth.uid()) with check (user_id = auth.uid());
-- No delete policy: rows are soft-deleted via deleted_at, never removed.

-- flashcard_decks -----------------------------------------------------------------
create table if not exists public.flashcard_decks (
  id uuid primary key,
  user_id uuid not null references auth.users (id) on delete cascade,
  created_at text not null,
  updated_at text not null,
  deleted_at text,
  rev bigint not null default 0,
  synced_at timestamptz not null default now(),
  name text not null,
  subject_id uuid,
  description text
);
create index if not exists idx_flashcard_decks_user_synced on public.flashcard_decks (user_id, synced_at);
drop trigger if exists trg_flashcard_decks_rev on public.flashcard_decks;
create trigger trg_flashcard_decks_rev before insert or update on public.flashcard_decks
  for each row execute function public.studyhub_bump_rev();
alter table public.flashcard_decks enable row level security;
drop policy if exists "flashcard_decks_owner_select" on public.flashcard_decks;
drop policy if exists "flashcard_decks_owner_insert" on public.flashcard_decks;
drop policy if exists "flashcard_decks_owner_update" on public.flashcard_decks;
create policy "flashcard_decks_owner_select" on public.flashcard_decks for select using (user_id = auth.uid());
create policy "flashcard_decks_owner_insert" on public.flashcard_decks for insert with check (user_id = auth.uid());
create policy "flashcard_decks_owner_update" on public.flashcard_decks for update using (user_id = auth.uid()) with check (user_id = auth.uid());
-- No delete policy: rows are soft-deleted via deleted_at, never removed.

-- flashcards -----------------------------------------------------------------
create table if not exists public.flashcards (
  id uuid primary key,
  user_id uuid not null references auth.users (id) on delete cascade,
  created_at text not null,
  updated_at text not null,
  deleted_at text,
  rev bigint not null default 0,
  synced_at timestamptz not null default now(),
  deck_id uuid not null,
  front text not null,
  back text not null,
  ease_factor double precision not null default 2.5,
  interval_days integer not null default 0,
  repetitions integer not null default 0,
  due_date text
);
create index if not exists idx_flashcards_user_synced on public.flashcards (user_id, synced_at);
drop trigger if exists trg_flashcards_rev on public.flashcards;
create trigger trg_flashcards_rev before insert or update on public.flashcards
  for each row execute function public.studyhub_bump_rev();
alter table public.flashcards enable row level security;
drop policy if exists "flashcards_owner_select" on public.flashcards;
drop policy if exists "flashcards_owner_insert" on public.flashcards;
drop policy if exists "flashcards_owner_update" on public.flashcards;
create policy "flashcards_owner_select" on public.flashcards for select using (user_id = auth.uid());
create policy "flashcards_owner_insert" on public.flashcards for insert with check (user_id = auth.uid());
create policy "flashcards_owner_update" on public.flashcards for update using (user_id = auth.uid()) with check (user_id = auth.uid());
-- No delete policy: rows are soft-deleted via deleted_at, never removed.

-- flashcard_reviews -----------------------------------------------------------------
create table if not exists public.flashcard_reviews (
  id uuid primary key,
  user_id uuid not null references auth.users (id) on delete cascade,
  created_at text not null,
  updated_at text not null,
  deleted_at text,
  rev bigint not null default 0,
  synced_at timestamptz not null default now(),
  card_id uuid not null,
  deck_id uuid not null,
  reviewed_on text not null,
  quality integer not null,
  was_new integer not null default 0
);
create index if not exists idx_flashcard_reviews_user_synced on public.flashcard_reviews (user_id, synced_at);
drop trigger if exists trg_flashcard_reviews_rev on public.flashcard_reviews;
create trigger trg_flashcard_reviews_rev before insert or update on public.flashcard_reviews
  for each row execute function public.studyhub_bump_rev();
alter table public.flashcard_reviews enable row level security;
drop policy if exists "flashcard_reviews_owner_select" on public.flashcard_reviews;
drop policy if exists "flashcard_reviews_owner_insert" on public.flashcard_reviews;
drop policy if exists "flashcard_reviews_owner_update" on public.flashcard_reviews;
create policy "flashcard_reviews_owner_select" on public.flashcard_reviews for select using (user_id = auth.uid());
create policy "flashcard_reviews_owner_insert" on public.flashcard_reviews for insert with check (user_id = auth.uid());
create policy "flashcard_reviews_owner_update" on public.flashcard_reviews for update using (user_id = auth.uid()) with check (user_id = auth.uid());
-- No delete policy: rows are soft-deleted via deleted_at, never removed.

-- grades -----------------------------------------------------------------
create table if not exists public.grades (
  id uuid primary key,
  user_id uuid not null references auth.users (id) on delete cascade,
  created_at text not null,
  updated_at text not null,
  deleted_at text,
  rev bigint not null default 0,
  synced_at timestamptz not null default now(),
  subject_id uuid not null,
  title text not null,
  value double precision not null,
  scale text not null,
  weight double precision not null default 1,
  date text not null
);
create index if not exists idx_grades_user_synced on public.grades (user_id, synced_at);
drop trigger if exists trg_grades_rev on public.grades;
create trigger trg_grades_rev before insert or update on public.grades
  for each row execute function public.studyhub_bump_rev();
alter table public.grades enable row level security;
drop policy if exists "grades_owner_select" on public.grades;
drop policy if exists "grades_owner_insert" on public.grades;
drop policy if exists "grades_owner_update" on public.grades;
create policy "grades_owner_select" on public.grades for select using (user_id = auth.uid());
create policy "grades_owner_insert" on public.grades for insert with check (user_id = auth.uid());
create policy "grades_owner_update" on public.grades for update using (user_id = auth.uid()) with check (user_id = auth.uid());
-- No delete policy: rows are soft-deleted via deleted_at, never removed.

-- files -----------------------------------------------------------------
create table if not exists public.files (
  id uuid primary key,
  user_id uuid not null references auth.users (id) on delete cascade,
  created_at text not null,
  updated_at text not null,
  deleted_at text,
  rev bigint not null default 0,
  synced_at timestamptz not null default now(),
  name text not null,
  mime_type text,
  size_bytes bigint not null default 0,
  local_path text,
  remote_path text,
  subject_id uuid,
  folder_id uuid,
  checksum_sha256 text,
  is_linked integer not null default 0,
  upload_status text not null default 'none'
);
create index if not exists idx_files_user_synced on public.files (user_id, synced_at);
drop trigger if exists trg_files_rev on public.files;
create trigger trg_files_rev before insert or update on public.files
  for each row execute function public.studyhub_bump_rev();
alter table public.files enable row level security;
drop policy if exists "files_owner_select" on public.files;
drop policy if exists "files_owner_insert" on public.files;
drop policy if exists "files_owner_update" on public.files;
create policy "files_owner_select" on public.files for select using (user_id = auth.uid());
create policy "files_owner_insert" on public.files for insert with check (user_id = auth.uid());
create policy "files_owner_update" on public.files for update using (user_id = auth.uid()) with check (user_id = auth.uid());
-- No delete policy: rows are soft-deleted via deleted_at, never removed.

-- documents -----------------------------------------------------------------
create table if not exists public.documents (
  id uuid primary key,
  user_id uuid not null references auth.users (id) on delete cascade,
  created_at text not null,
  updated_at text not null,
  deleted_at text,
  rev bigint not null default 0,
  synced_at timestamptz not null default now(),
  title text not null,
  doc_type text not null,
  content_json text not null default '{}',
  folder_id uuid
);
create index if not exists idx_documents_user_synced on public.documents (user_id, synced_at);
drop trigger if exists trg_documents_rev on public.documents;
create trigger trg_documents_rev before insert or update on public.documents
  for each row execute function public.studyhub_bump_rev();
alter table public.documents enable row level security;
drop policy if exists "documents_owner_select" on public.documents;
drop policy if exists "documents_owner_insert" on public.documents;
drop policy if exists "documents_owner_update" on public.documents;
create policy "documents_owner_select" on public.documents for select using (user_id = auth.uid());
create policy "documents_owner_insert" on public.documents for insert with check (user_id = auth.uid());
create policy "documents_owner_update" on public.documents for update using (user_id = auth.uid()) with check (user_id = auth.uid());
-- No delete policy: rows are soft-deleted via deleted_at, never removed.

-- Storage ------------------------------------------------------------------------
-- One bucket per user, named after the user id. The client creates it on first
-- upload; these policies allow exactly that and nothing else.
drop policy if exists "studyhub_bucket_select" on storage.buckets;
drop policy if exists "studyhub_bucket_insert" on storage.buckets;
create policy "studyhub_bucket_select" on storage.buckets for select using (id = auth.uid()::text);
create policy "studyhub_bucket_insert" on storage.buckets for insert with check (id = auth.uid()::text);

drop policy if exists "studyhub_objects_select" on storage.objects;
drop policy if exists "studyhub_objects_insert" on storage.objects;
drop policy if exists "studyhub_objects_update" on storage.objects;
drop policy if exists "studyhub_objects_delete" on storage.objects;
create policy "studyhub_objects_select" on storage.objects for select using (bucket_id = auth.uid()::text);
create policy "studyhub_objects_insert" on storage.objects for insert with check (bucket_id = auth.uid()::text);
create policy "studyhub_objects_update" on storage.objects for update using (bucket_id = auth.uid()::text) with check (bucket_id = auth.uid()::text);
create policy "studyhub_objects_delete" on storage.objects for delete using (bucket_id = auth.uid()::text);
