/** Keys of the `settings` table (device-local, JSON values). */
export const SETTINGS = {
  setupCompleted: "setup.completed",
  profile: "profile",
  mode: "storage.mode",
  workingFolder: "storage.workingFolder",
  linkFilesInsteadOfCopy: "storage.linkFiles",
  autoUpload: "storage.autoUpload",
  gradeScale: "grades.scale",
  gradesWeighted: "grades.weighted",
  gradesEnabled: "grades.enabled",
  flashcardsDailyNew: "flashcards.dailyNew",
  flashcardsIntensity: "flashcards.intensity",
  notificationsEnabled: "notifications.enabled",
  notificationsLeadMinutes: "notifications.leadMinutes",
  dailyReminderTime: "notifications.dailyReminderTime",
  aiEnabled: "ai.enabled",
  timetableDays: "timetable.days",
  timetableLessonsPerDay: "timetable.lessonsPerDay",
  timetableLessonTimes: "timetable.lessonTimes",
  timetableAbWeeks: "timetable.abWeeks",
  timetableWeekAStart: "timetable.weekAStart",
  dashboardLayout: "dashboard.layout",
  modulesVisible: "modules.visible",
  lastSyncAt: "sync.lastSyncAt",
  lastBackupDate: "backup.lastDate",
} as const;
